# Generated by Django 5.0.4 on 2024-05-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type_error', models.CharField(max_length=30)),
                ('about_error', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='my_gallery')),
            ],
        ),
    ]
