# Generated by Django 5.0.4 on 2024-05-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_errormessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type_inaccuracy', models.CharField(max_length=50)),
                ('about_inaccuracy', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='info_gallery')),
            ],
        ),
        migrations.AlterField(
            model_name='errormessage',
            name='image',
            field=models.FileField(blank=True, upload_to='error_gallery'),
        ),
        migrations.AlterField(
            model_name='errormessage',
            name='type_error',
            field=models.CharField(max_length=50),
        ),
    ]
