# Generated by Django 5.0.4 on 2024-05-28 10:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutGrape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rus', models.CharField(max_length=50)),
                ('about_grape', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)])),
                ('area', models.IntegerField(null=True)),
                ('image', models.FileField(blank=True, upload_to='grape_gallery')),
                ('slug', models.SlugField(default='', unique=True)),
                ('about_grape', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='info_about_grape', to='grape_varieties.aboutgrape')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colors', to='grape_varieties.category')),
            ],
        ),
    ]
