# Generated by Django 5.0.4 on 2024-05-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grape_varieties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagGrape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='grape',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='grape_varieties.taggrape'),
        ),
    ]
