# Generated by Django 5.0.4 on 2024-06-04 09:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grape_varieties', '0002_taggrape_grape_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('the_story', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='TagHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_name', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, upload_to='grape_gallery')),
                ('slug', models.SlugField(default='', unique=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='once_history', to='grape_varieties.abouthistory')),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='grape_varieties.taghistory')),
            ],
        ),
    ]
